listaLugares = ["paris", "roma", "egipto", "atenas", "dublin"]
print(listaLugares)
sorte = sorted(listaLugares)
print("orden alfabetico ", sorte)
print(listaLugares)
alreves = sorted(listaLugares, reverse=True)
print("orden alfabetico al reves ", alreves)
print(listaLugares)
listaLugares.reverse()
print("desorden ",listaLugares)
listaLugares.reverse()
print("orden ",listaLugares)
listaLugares.sort()
print("alfabetico ",listaLugares)
listaLugares.sort(reverse=True)
print("inverso alfabetico",listaLugares)